"""Dynamixel operating mode constants."""

# Control table addresses (X-series)
ADDR_OPERATING_MODE = 11
ADDR_TORQUE_ENABLE = 64
ADDR_GOAL_POSITION = 116
ADDR_GOAL_CURRENT = 102
ADDR_PRESENT_POSITION = 132
ADDR_PRESENT_VELOCITY = 128
ADDR_PRESENT_CURRENT = 126
ADDR_PRESENT_PWM = 124
ADDR_PRESENT_INPUT_VOLTAGE = 144
ADDR_BUS_WATCHDOG = 98
ADDR_PROFILE_VELOCITY = 112
ADDR_PROFILE_ACCELERATION = 108

# Operating modes
MODE_CURRENT = 0
MODE_VELOCITY = 1
MODE_POSITION = 3
MODE_EXTENDED_POSITION = 4
MODE_CURRENT_BASED_POSITION = 5
MODE_PWM = 16

# Protocol
PROTOCOL_VERSION = 2.0


class DxlModes:
    JOINT = "joint"
    CURRENT_BASED_POSITION = "current_based_position"
