# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import robot_interface_pb2 as robot__interface__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in robot_interface_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotControllerStub(object):
    """Robot Interface Service
    Defines communication between Async DP and external robot controllers
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/asyncdp.RobotController/GetState',
                request_serializer=robot__interface__pb2.StateRequest.SerializeToString,
                response_deserializer=robot__interface__pb2.RobotState.FromString,
                _registered_method=True)
        self.SendAction = channel.unary_unary(
                '/asyncdp.RobotController/SendAction',
                request_serializer=robot__interface__pb2.ActionCommand.SerializeToString,
                response_deserializer=robot__interface__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.SendTrajectory = channel.unary_unary(
                '/asyncdp.RobotController/SendTrajectory',
                request_serializer=robot__interface__pb2.TrajectoryCommand.SerializeToString,
                response_deserializer=robot__interface__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StreamControl = channel.stream_stream(
                '/asyncdp.RobotController/StreamControl',
                request_serializer=robot__interface__pb2.ActionCommand.SerializeToString,
                response_deserializer=robot__interface__pb2.RobotState.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/asyncdp.RobotController/GetStatus',
                request_serializer=robot__interface__pb2.StatusRequest.SerializeToString,
                response_deserializer=robot__interface__pb2.ControllerStatus.FromString,
                _registered_method=True)


class RobotControllerServicer(object):
    """Robot Interface Service
    Defines communication between Async DP and external robot controllers
    """

    def GetState(self, request, context):
        """Get current robot state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAction(self, request, context):
        """Send single action command
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTrajectory(self, request, context):
        """Send full action trajectory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamControl(self, request_iterator, context):
        """Bidirectional streaming for real-time control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get controller status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=robot__interface__pb2.StateRequest.FromString,
                    response_serializer=robot__interface__pb2.RobotState.SerializeToString,
            ),
            'SendAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAction,
                    request_deserializer=robot__interface__pb2.ActionCommand.FromString,
                    response_serializer=robot__interface__pb2.CommandResponse.SerializeToString,
            ),
            'SendTrajectory': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTrajectory,
                    request_deserializer=robot__interface__pb2.TrajectoryCommand.FromString,
                    response_serializer=robot__interface__pb2.CommandResponse.SerializeToString,
            ),
            'StreamControl': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamControl,
                    request_deserializer=robot__interface__pb2.ActionCommand.FromString,
                    response_serializer=robot__interface__pb2.RobotState.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=robot__interface__pb2.StatusRequest.FromString,
                    response_serializer=robot__interface__pb2.ControllerStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'asyncdp.RobotController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('asyncdp.RobotController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotController(object):
    """Robot Interface Service
    Defines communication between Async DP and external robot controllers
    """

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asyncdp.RobotController/GetState',
            robot__interface__pb2.StateRequest.SerializeToString,
            robot__interface__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asyncdp.RobotController/SendAction',
            robot__interface__pb2.ActionCommand.SerializeToString,
            robot__interface__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asyncdp.RobotController/SendTrajectory',
            robot__interface__pb2.TrajectoryCommand.SerializeToString,
            robot__interface__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamControl(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/asyncdp.RobotController/StreamControl',
            robot__interface__pb2.ActionCommand.SerializeToString,
            robot__interface__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asyncdp.RobotController/GetStatus',
            robot__interface__pb2.StatusRequest.SerializeToString,
            robot__interface__pb2.ControllerStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
